#pragma once

enum class text_color: WORD {
    Black = 0,
    Blue = FOREGROUND_BLUE,
    Green = FOREGROUND_GREEN,
    Cyan = FOREGROUND_GREEN | FOREGROUND_BLUE,
    Red = FOREGROUND_RED,
    Magenta = FOREGROUND_RED | FOREGROUND_BLUE,
    Yellow = FOREGROUND_RED | FOREGROUND_GREEN,
    White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    BrightBlack = 0 | FOREGROUND_INTENSITY,
    BrightBlue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightGreen = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    BrightCyan = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightRed = FOREGROUND_RED | FOREGROUND_INTENSITY,
    BrightMagenta = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightYellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    BrightWhite = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
};

enum class bg_color : WORD {
    Black = 0,
    Blue = BACKGROUND_BLUE,
    Green = BACKGROUND_GREEN,
    Cyan = BACKGROUND_GREEN | BACKGROUND_BLUE,
    Red = BACKGROUND_RED,
    Magenta = BACKGROUND_RED | BACKGROUND_BLUE,
    Yellow = BACKGROUND_RED | BACKGROUND_GREEN,
    White = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BrightBlack = 0 | BACKGROUND_INTENSITY,
    BrightBlue = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BrightGreen = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
    BrightCyan = BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BrightRed = BACKGROUND_RED | BACKGROUND_INTENSITY,
    BrightMagenta = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BrightYellow = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY,
    BrightWhite = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
};